// <auto-generated />
using System;
using Autoceste.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Autoceste.DAL.Migrations
{
    [DbContext(typeof(OrContext))]
    partial class OrContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Autoceste.DAL.Models.Autoceste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dionica")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dionica");

                    b.Property<double>("Duljina")
                        .HasColumnType("double precision")
                        .HasColumnName("duljina");

                    b.Property<string>("Neformalninaziv")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("neformalninaziv");

                    b.Property<string>("Oznaka")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("oznaka");

                    b.HasKey("Id")
                        .HasName("autoceste_pkey");

                    b.ToTable("autoceste", (string)null);
                });

            modelBuilder.Entity("Autoceste.DAL.Models.Naplatnepostaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Autocestaid")
                        .HasColumnType("integer")
                        .HasColumnName("autocestaid");

                    b.Property<double?>("Geoduzina")
                        .HasColumnType("double precision")
                        .HasColumnName("geoduzina");

                    b.Property<double?>("Geosirina")
                        .HasColumnType("double precision")
                        .HasColumnName("geosirina");

                    b.Property<bool?>("Imaenc")
                        .HasColumnType("boolean")
                        .HasColumnName("imaenc");

                    b.Property<string>("Kontakt")
                        .HasColumnType("text")
                        .HasColumnName("kontakt");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("naziv");

                    b.HasKey("Id")
                        .HasName("naplatnepostaje_pkey");

                    b.HasIndex("Autocestaid");

                    b.ToTable("naplatnepostaje", (string)null);
                });

            modelBuilder.Entity("Autoceste.DAL.Models.Naplatnepostaje", b =>
                {
                    b.HasOne("Autoceste.DAL.Models.Autoceste", "Autocesta")
                        .WithMany("Naplatnepostajes")
                        .HasForeignKey("Autocestaid")
                        .HasConstraintName("naplatnepostaje_autocestaid_fkey");

                    b.Navigation("Autocesta");
                });

            modelBuilder.Entity("Autoceste.DAL.Models.Autoceste", b =>
                {
                    b.Navigation("Naplatnepostajes");
                });
#pragma warning restore 612, 618
        }
    }
}
